### ISSUE TITLE
[CM 13 - chagalllte] Camera and DRM issue

### ISSUE THREAD

**Issue by chaos234** [CM-Tab-S/android_kernel_samsung_klimtwifi#3]
Hey,

I found this repro from http://forum.xda-developers.com/galaxy-tab-s/development/rom-cyanogenmod-13-0-sm-t805-t3320365/ but the branch for chagalllte is not available anymore so I report this issue here until it is fixed.

I dunno why the camera is not working, also why the DRM content does not work but a fix must be deliveerd since it is requests since the release.

Please provide a new version with the bugfixes, thanks.

**Comment by deadman96385** [comment]
https://github.com/exynos5420/android_kernel_samsung_exynos5420
